(in-package :redis-client)

(defcmd ping)
(defcmd exists key)
(defcmd del key)
(defcmd type key)
(defcmd lpush key val)
(defcmd rpoplpush key1 key2)
(defcmd randomkey)
(defcmd rename oldkey newkey)
(defcmd renamenx oldkey newkey)
(defcmd dbsize)
(defcmd expire key seconds)
(defcmd persist key)
(defcmd ttl key)
(defcmd select db)
(defcmd move key db)
(defcmd flushdb)
(defcmd flushall)

(defcmd set key val)
(defcmd get key)
(defcmd getset key val)
(defcmd incr key)
(defcmd incrby key int)
(defcmd decr key)
(defcmd decrby key int)

(defcmd sadd key val)
(defcmd srem key val)
(defcmd scard key)
(defcmd smembers key)
(defcmd smove key1 key2 value)
(defcmd sismember key value)

(defcmd lrange key n1 &optional n2)
